import Foundation

// Updater safety (review 5A-11, 5A-12, 5A-25).
//
// The install script is generated by `UpdateService.installScript()` and run
// with the new bundle and the destination as *arguments*, so these tests run
// the real script — against temp directories only. Nothing here touches
// `/Applications`, and the script's optional 3rd/4th arguments skip its two
// second wait and its relaunch so a test can never open anything. The
// failure branch is exercised on purpose, so `PATH` is also stubbed: the
// script's `osascript` alert is captured to a log file and never displayed.
enum UpdateServiceTests {
    static let tests: [(String, () throws -> Void)] = [
        ("installScript_replacesTheAppAndLeavesNoStagingDirs", testInstallHappyPath),
        ("installScript_keepsTheOldAppWhenTheCopyFails", testInstallCopyFailureKeepsOldApp),
        ("installScript_installsWhenNothingIsThereYet", testInstallFreshDestination),
        ("installScript_handlesPathsWithSpacesAndQuotes", testInstallAwkwardPaths),
        ("signing_parsesIdentifierAndAuthorityChain", testParseSigningInfo),
        ("signing_refusesAForeignSignerOrWrongBundleID", testIdentityMismatch),
        ("signing_acceptsTheSameChainAndBundleID", testIdentityMatch),
    ]

    // MARK: - Script harness

    /// Runs the generated installer in a sandbox.
    ///
    /// Three things keep this off the user's machine: the paths are temp
    /// directories (never `/Applications`), the script's 4th argument
    /// disables its relaunch step, and `PATH` is prefixed with a stub
    /// `osascript` that appends to a log **instead of putting a real alert on
    /// the user's screen** — the failure branch below is exercised
    /// deliberately, so it must never be able to display anything.
    ///
    /// Returns the exit status and whatever the script tried to alert about.
    private static func runInstaller(
        newApp: URL,
        target: URL,
        in dir: URL
    ) throws -> (status: Int32, alerts: String) {
        let scriptURL = dir.appendingPathComponent("install.sh")
        try UpdateService.installScript().write(to: scriptURL, atomically: true, encoding: .utf8)

        // Stub bin dir: `osascript` logs its arguments and exits 0.
        let stubBin = dir.appendingPathComponent("stub-bin")
        try FileManager.default.createDirectory(at: stubBin, withIntermediateDirectories: true)
        let alertLog = dir.appendingPathComponent("alerts.log")
        let stub = """
        #!/bin/bash
        printf '%s\\n' "$*" >> "\(alertLog.path)"
        exit 0
        """
        let stubURL = stubBin.appendingPathComponent("osascript")
        try stub.write(to: stubURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: stubURL.path)

        var environment = ProcessInfo.processInfo.environment
        environment["PATH"] = "\(stubBin.path):\(environment["PATH"] ?? "/usr/bin:/bin")"

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        // "0" = do not sleep, "0" = do not relaunch anything.
        process.arguments = [scriptURL.path, newApp.path, target.path, "0", "0"]
        process.environment = environment
        process.standardOutput = Pipe()
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()

        let alerts = (try? String(contentsOf: alertLog, encoding: .utf8)) ?? ""
        return (process.terminationStatus, alerts)
    }

    /// Writes a stand-in for an .app bundle: a directory with one marker file.
    private static func makeBundle(at url: URL, marker: String) throws {
        try FileManager.default.createDirectory(
            at: url.appendingPathComponent("Contents"),
            withIntermediateDirectories: true
        )
        try marker.write(
            to: url.appendingPathComponent("Contents/marker.txt"),
            atomically: true,
            encoding: .utf8
        )
    }

    private static func marker(of bundle: URL) -> String? {
        try? String(contentsOf: bundle.appendingPathComponent("Contents/marker.txt"), encoding: .utf8)
    }

    private static func exists(_ url: URL) -> Bool {
        FileManager.default.fileExists(atPath: url.path)
    }

    // MARK: - 5A-11: never leave the user without an app

    static func testInstallHappyPath() throws {
        try withTempDir { dir in
            let newApp = dir.appendingPathComponent("extracted/Klip.app")
            let target = dir.appendingPathComponent("Applications/Klip.app")
            try makeBundle(at: newApp, marker: "new")
            try makeBundle(at: target, marker: "old")

            let run = try runInstaller(newApp: newApp, target: target, in: dir)
            try expectEqual(run.status, 0, "a clean install should succeed")
            try expect(run.alerts.isEmpty, "a successful install shows no alert")
            try expectEqual(marker(of: target), "new", "the new bundle should be in place")
            try expect(!exists(target.appendingPathComponent("../Klip.app.new").standardizedFileURL),
                       "no staging copy should be left behind")
            try expect(!exists(URL(fileURLWithPath: target.path + ".old")),
                       "the old bundle should be cleaned up")
        }
    }

    /// The finding itself: the old script did `rm -rf` first, so a failing
    /// copy left the user with nothing.
    static func testInstallCopyFailureKeepsOldApp() throws {
        try withTempDir { dir in
            let missingNewApp = dir.appendingPathComponent("extracted/Klip.app")  // never created
            let target = dir.appendingPathComponent("Applications/Klip.app")
            try makeBundle(at: target, marker: "old")

            let run = try runInstaller(newApp: missingNewApp, target: target, in: dir)
            try expect(run.status != 0, "a failed install must report failure")
            try expect(run.alerts.contains("Could not stage the new app"),
                       "the user is told what went wrong (captured from a stubbed osascript, never displayed)")
            try expect(exists(target), "the installed app must survive a failed update")
            try expectEqual(marker(of: target), "old", "…and must still be the old bundle, intact")
            try expect(!exists(URL(fileURLWithPath: target.path + ".new")),
                       "no staging copy should be left behind")
        }
    }

    static func testInstallFreshDestination() throws {
        try withTempDir { dir in
            let newApp = dir.appendingPathComponent("extracted/Klip.app")
            let target = dir.appendingPathComponent("Applications/Klip.app")
            try makeBundle(at: newApp, marker: "new")
            try FileManager.default.createDirectory(
                at: target.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )

            let run = try runInstaller(newApp: newApp, target: target, in: dir)
            try expectEqual(run.status, 0, "installing where nothing exists should succeed")
            try expectEqual(marker(of: target), "new")
        }
    }

    /// 5A-25: paths reach the script as arguments, so spaces and quotes in
    /// `TMPDIR` (or anywhere else) cannot break or inject into it.
    static func testInstallAwkwardPaths() throws {
        try withTempDir { dir in
            let awkward = dir.appendingPathComponent("we ird 'dir\" $HOME")
            let newApp = awkward.appendingPathComponent("extracted/Klip.app")
            let target = awkward.appendingPathComponent("Applications/Klip.app")
            try makeBundle(at: newApp, marker: "new")
            try makeBundle(at: target, marker: "old")

            let run = try runInstaller(newApp: newApp, target: target, in: dir)
            try expectEqual(run.status, 0, "an awkward path should still install")
            try expectEqual(marker(of: target), "new")
        }
    }

    // MARK: - 5A-12: identity, not just signature validity

    static func testParseSigningInfo() throws {
        let sample = """
        Executable=/Applications/Klip.app/Contents/MacOS/Klip
        Identifier=com.fxreza.klip
        Format=app bundle with Mach-O thin (arm64)
        CodeDirectory v=20400 size=1234 flags=0x0(none) hashes=30+7
        Signature size=1234
        Authority=QTranslate Dev
        Info.plist entries=10
        Sealed Resources version=2 rules=13 files=5
        """
        let info = UpdateService.parseSigningInfo(sample)
        try expectEqual(info.identifier, "com.fxreza.klip")
        try expectEqual(info.authorities, ["QTranslate Dev"])

        let adhoc = UpdateService.parseSigningInfo("Identifier=com.fxreza.klip\nSignature=adhoc\n")
        try expectEqual(adhoc.authorities, [], "an ad-hoc signature has no authority chain")
    }

    static func testIdentityMismatch() throws {
        let running = UpdateService.SigningInfo(identifier: "com.fxreza.klip", authorities: ["QTranslate Dev"])

        // Signed by someone else entirely — exactly what `codesign --verify`
        // used to wave through.
        let foreign = UpdateService.SigningInfo(
            identifier: "com.fxreza.klip",
            authorities: ["Developer ID Application: Someone Else (ABCDE12345)", "Apple Root CA"]
        )
        try expectNotNil(UpdateService.identityMismatchReason(candidate: foreign, running: running),
                         "a different signer must be refused")

        // Ad-hoc / unsigned build offered to a signed install.
        let adhoc = UpdateService.SigningInfo(identifier: "com.fxreza.klip", authorities: [])
        try expectNotNil(UpdateService.identityMismatchReason(candidate: adhoc, running: running),
                         "an unsigned bundle must be refused")

        // Right signer, wrong app.
        let otherApp = UpdateService.SigningInfo(identifier: "com.example.other", authorities: ["QTranslate Dev"])
        try expectNotNil(UpdateService.identityMismatchReason(candidate: otherApp, running: running),
                         "a bundle identifier that is not Klip must be refused")

        // Unreadable identifier.
        let noID = UpdateService.SigningInfo(identifier: nil, authorities: ["QTranslate Dev"])
        try expectNotNil(UpdateService.identityMismatchReason(candidate: noID, running: running),
                         "a bundle with no identifier must be refused")
    }

    static func testIdentityMatch() throws {
        let running = UpdateService.SigningInfo(
            identifier: "com.fxreza.klip",
            authorities: ["QTranslate Dev"]
        )
        let candidate = UpdateService.SigningInfo(
            identifier: "com.fxreza.klip",
            authorities: ["QTranslate Dev"]
        )
        try expectNil(UpdateService.identityMismatchReason(candidate: candidate, running: running),
                      "the same signer and bundle id installs")
    }
}
