import Foundation
import AppKit
import Combine
import UniformTypeIdentifiers

/// Monitors the system clipboard for changes and captures new content
class ClipboardWatcher: ObservableObject {
    @Published private(set) var isPaused = false
    
    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private var lastContentHash: Int = 0
    private var ignoreNextChange = false

    /// Fingerprint of the last captured file set, kept separate from
    /// `lastContentHash` (text/image use an `Int`; files use a SHA-256 hex
    /// string from `ClipboardStore.makeFileItem`) so a file capture and a
    /// text/image capture never accidentally compare equal.
    private var lastFileFingerprint: String?
    
    private let pollInterval: TimeInterval = 0.5

    // Size thresholds for text handling
    private let inlineTextLimit = 50_000       // 50 KB — store inline
    private let previewLength = 500            // Characters kept as inline preview

    /// Where the expensive half of a text capture runs (review 5A-04).
    ///
    /// The poll itself must stay on the main run loop (it reads
    /// `NSPasteboard.general`), but classification and the `texts/`,
    /// `flavors/` disk writes do not: a 14.9 MB clip used to block main for
    /// 5.0 s inside `ContentDetector.detect`, with the menu bar, the panel and
    /// the hotkey all dead for the duration. **Serial** so two captures can
    /// never land in `store.add` out of order; dedupe is unaffected because
    /// `lastContentHash` is still updated synchronously on main before the
    /// hand-off.
    private let captureQueue = DispatchQueue(label: "com.fxreza.klip.capture", qos: .utility)

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
        
        // Listen for ignore notification (when copying from history)
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleIgnoreNextChange),
            name: .bufferIgnoreNextChange,
            object: nil
        )
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    @objc private func handleIgnoreNextChange() {
        ignoreNextChange = true
    }
    
    func startWatching() {
        guard timer == nil else { return }
        
        timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
        
        RunLoop.main.add(timer!, forMode: .common)
    }
    
    func stopWatching() {
        timer?.invalidate()
        timer = nil
    }
    
    func pause() {
        isPaused = true
    }
    
    func resume() {
        isPaused = false
        lastChangeCount = NSPasteboard.general.changeCount
    }
    
    private func checkClipboard() {
        capture(from: NSPasteboard.general)
    }

    /// One poll tick against `pasteboard`.
    ///
    /// Split out of `checkClipboard()` so tests and the perf harness can drive
    /// exactly this code path against a private `NSPasteboard(name:)` instead
    /// of the user's real clipboard.
    func capture(from pasteboard: NSPasteboard) {
        guard !isPaused else { return }

        let currentChangeCount = pasteboard.changeCount
        
        // No change detected
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        
        // Skip if this is a copy from our own history
        if ignoreNextChange {
            ignoreNextChange = false
            return
        }
        
        // Honor org.nspasteboard.ConcealedType/TransientType/AutoGeneratedType
        // (password managers and similar tools opt out of clipboard history
        // this way) — skip the capture entirely, not just the rich flavors.
        if PasteboardFlavors.isConcealed(pasteboard) { return }

        // Get current frontmost app as source
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Check for file URLs from Finder BEFORE the text check (Finder always
        // writes both NSFilenamesPboardType + .string, so we must intercept first).
        // A single image file keeps today's behavior and becomes an `.image`
        // item; any other file, or any count/mix of files, becomes one `.file`
        // item (Phase 3F).
        if let filePaths = pasteboard.propertyList(forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")) as? [String],
           !filePaths.isEmpty {
            if filePaths.count == 1, let filePath = filePaths.first, isImageFile(filePath) {
                // Read and process image file asynchronously to avoid blocking the poll timer
                // 5A-29: `lastContentHash` is read here, on main, and passed
                // in — the background closure never reads watcher state.
                let knownHash = lastContentHash
                DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                    self?.processImageFile(filePath, knownHash: knownHash, sourceApp: sourceApp)
                }
                return  // Prevent .string branch from also processing this change
            }

            let urls = filePaths.map { URL(fileURLWithPath: $0) }
            // 5A-29: the last fingerprint is read here, on the main thread that
            // owns it, and passed into the background closure instead of being
            // read across threads.
            let previousFingerprint = lastFileFingerprint
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                self?.processFileURLs(urls, sourceApp: sourceApp, previousFingerprint: previousFingerprint)
            }
            return  // Prevent .string branch from also processing this change
        }
        
        // Try to capture text first
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let textSize = text.utf8.count
            
            // Use prefix hash for large text to avoid expensive full-string hashing
            let hashSource = textSize > inlineTextLimit ? String(text.prefix(10_000)) : text
            let hash = hashSource.hashValue
            
            // Skip consecutive duplicates
            if hash != lastContentHash {
                lastContentHash = hash

                // Rich capture (Phase 3D, D5): alongside the plain string,
                // read the RTF/HTML representation and the full raw pasteboard
                // flavors bundle. Applies regardless of inline-vs-file-backed
                // text size — a large plain-text clip can still carry a small
                // RTF/flavors payload worth keeping.
                // Cap the RTF blob like the raw-flavors bundle (review-2B M1): an
                // oversized RTF representation is dropped, the plain text is kept.
                //
                // These three reads stay on main: they read the pasteboard,
                // which must not be touched after the poll returns (its
                // contents can change under us).
                let rtfData = pasteboard.data(forType: .rtf).flatMap { $0.count <= PasteboardFlavors.maxRawBytes ? $0 : nil }
                let htmlData = pasteboard.data(forType: .html)
                let isRich = rtfData != nil || htmlData != nil
                let flavorsData = PasteboardFlavors.capture(pasteboard)

                // Everything past this point is classification and disk I/O
                // over data we already hold — no pasteboard access — so it
                // runs off the main thread (5A-04) and hops back only for
                // `store.add`.
                captureQueue.async { [weak self] in
                    self?.finishTextCapture(
                        text: text,
                        textSize: textSize,
                        sourceApp: sourceApp,
                        rtfData: rtfData,
                        flavorsData: flavorsData,
                        isRich: isRich
                    )
                }
            }
            return
        }
        
        // Try to capture image. The pasteboard read stays on main; the disk
        // write (and, only on the fallback path, the PNG re-encode — a full
        // decode + re-compress, tens of ms for a retina screenshot) go to
        // `captureQueue`, like the text branch above (5A-04).
        //
        // Verbatim path first (6C): a JPEG/PNG/HEIC/GIF/WebP already on the
        // pasteboard is stored byte-for-byte, under its real extension — no
        // decode, no re-encode, no size cap. Only when none of those five
        // representations are present (TIFF-only, or a vector/PDF image
        // type) do we fall back to today's NSImage -> PNG conversion, which
        // is where the 4096 px cap applies (see `pngData(from:)`).
        if let verbatim = verbatimImageData(from: pasteboard) {
            let knownHash = lastContentHash
            captureQueue.async { [weak self] in
                self?.finishImageCapture(
                    verbatim.data,
                    fileExtension: verbatim.fileExtension,
                    uti: verbatim.uti,
                    knownHash: knownHash,
                    sourceApp: sourceApp
                )
            }
        } else if let rawImageData = rawImageData(from: pasteboard) {
            // 5A-29: read `lastContentHash` here, on main, instead of from
            // the background closure.
            let knownHash = lastContentHash
            captureQueue.async { [weak self] in
                self?.finishImageCaptureFallback(rawImageData, knownHash: knownHash, sourceApp: sourceApp)
            }
        }
    }

    /// One of the five raster representations `verbatimImageData` looked for
    /// on the pasteboard, kept exactly as captured.
    private struct VerbatimImage {
        let data: Data
        let fileExtension: String
        let uti: String
    }

    /// Picks the first available image representation on `pasteboard` in
    /// verbatim-preserving order — `public.jpeg` -> `.jpg`, `public.png` ->
    /// `.png`, `public.heic` -> `.heic`, `com.compuserve.gif` -> `.gif`,
    /// `public.webp` -> `.webp` — or `nil` if none of the five are present,
    /// in which case the caller falls back to `rawImageData`/`pngData`.
    private func verbatimImageData(from pasteboard: NSPasteboard) -> VerbatimImage? {
        let candidates: [(NSPasteboard.PasteboardType, String, String)] = [
            (NSPasteboard.PasteboardType("public.jpeg"), "jpg", "public.jpeg"),
            (.png, "png", "public.png"),
            (NSPasteboard.PasteboardType("public.heic"), "heic", "public.heic"),
            (NSPasteboard.PasteboardType("com.compuserve.gif"), "gif", "com.compuserve.gif"),
            (NSPasteboard.PasteboardType("public.webp"), "webp", "public.webp"),
        ]
        for (type, ext, uti) in candidates {
            if let data = pasteboard.data(forType: type) {
                return VerbatimImage(data: data, fileExtension: ext, uti: uti)
            }
        }
        return nil
    }

    /// Background half of a verbatim pasteboard image capture (6C): the
    /// bytes are stored exactly as received, so the dedupe hash is the hash
    /// of those same bytes.
    private func finishImageCapture(_ data: Data, fileExtension: String, uti: String, knownHash: Int, sourceApp: String?) {
        let hash = data.hashValue

        // Skip consecutive duplicates
        guard hash != knownHash else { return }

        guard let filename = store.saveImage(data, fileExtension: fileExtension) else { return }
        var item = ClipboardItem.image(filename: filename, uti: uti, sourceApp: sourceApp)
        item.kind = .image
        let captured = item
        DispatchQueue.main.async { [weak self] in
            self?.lastContentHash = hash
            self?.store.add(captured)
        }
    }

    /// Background half of a pasteboard image capture with no verbatim raster
    /// representation available (TIFF-only, or a vector/PDF image type):
    /// decode via `NSImage` and re-encode as PNG. This is the only image
    /// capture path the 4096 px cap applies to.
    private func finishImageCaptureFallback(_ rawImageData: Data, knownHash: Int, sourceApp: String?) {
        guard let imageData = pngData(from: rawImageData) else { return }
        let hash = imageData.hashValue

        // Skip consecutive duplicates
        guard hash != knownHash else { return }

        guard let filename = store.saveImage(imageData, fileExtension: "png") else { return }
        var item = ClipboardItem.image(filename: filename, uti: "public.png", sourceApp: sourceApp)
        item.kind = .image
        let captured = item
        DispatchQueue.main.async { [weak self] in
            self?.lastContentHash = hash
            self?.store.add(captured)
        }
    }
    
    /// The expensive half of a text capture, run on `captureQueue`.
    ///
    /// Classification (`ContentDetector`, itself `nonisolated` and now capped
    /// at `detectionInputLimit`) plus the `texts/` and `flavors/` writes. The
    /// `store.save*` helpers it calls are pure file writes against immutable
    /// directory URLs — they touch no `ClipboardStore` state — which is the
    /// same contract `processImageFile` has relied on for `saveImage` since
    /// before this change. The item is handed to `store.add` back on main.
    private func finishTextCapture(
        text: String,
        textSize: Int,
        sourceApp: String?,
        rtfData: Data?,
        flavorsData: Data?,
        isRich: Bool
    ) {
        var item: ClipboardItem
        if textSize <= inlineTextLimit {
            // Small text: store inline (current behavior)
            item = ClipboardItem.text(text, sourceApp: sourceApp)
        } else {
            // Large text: save to file, store preview inline
            let preview = String(text.prefix(previewLength))
            guard let filename = store.saveText(text) else { return }
            item = ClipboardItem.largeText(preview: preview, filename: filename, sourceApp: sourceApp)
            print("[Buffer] Large text (\(textSize / 1024) KB) saved to file: \(filename)")
        }

        // Detect against the full captured text (not just an inline
        // preview) — we already have it in memory here. 3C's detector
        // result (link/email/phone/color/code) is kept as-is; only a
        // plain `.text` result is upgraded to `.richText`.
        var kind = ContentDetector.detect(for: item, fullText: text)
        if isRich && kind == .text {
            kind = .richText
        }
        item.kind = kind

        if let rtfData, let filename = store.saveRTF(rtfData, itemID: item.id) {
            item.rtfFilename = filename
        }
        if let flavorsData, let filename = store.saveFlavors(flavorsData, itemID: item.id) {
            item.flavorsFilename = filename
        }

        let captured = item
        DispatchQueue.main.async { [weak self] in
            self?.store.add(captured)
        }
    }

    /// The raw `.tiff` bytes on the pasteboard, if any — the "no verbatim
    /// raster representation" fallback case (`.png`/`.jpeg`/etc are all
    /// handled by `verbatimImageData` before this is ever reached). Cheap
    /// enough to run on the poll thread; the conversion below is not.
    private func rawImageData(from pasteboard: NSPasteboard) -> Data? {
        pasteboard.data(forType: .tiff)
    }

    /// Longest edge, in pixels, a fallback-path PNG is allowed to keep.
    /// Verbatim JPEG/PNG/HEIC/GIF/WebP captures never go through this
    /// function and are stored at their original size no matter how large.
    /// `nonisolated` so the `nonisolated` `pngData(from:)` below (itself
    /// off-main so a large decode/re-encode never blocks the poll timer)
    /// can read it without hopping to the main actor.
    private nonisolated static let fallbackMaxDimension: CGFloat = 4096

    /// Normalises arbitrary image bytes to PNG, downscaled to at most
    /// `fallbackMaxDimension` px on the long edge. Used only for the
    /// TIFF-only / vector-PDF fallback path — every verbatim raster capture
    /// bypasses this entirely and keeps its original bytes and size.
    /// Returns `nil` when the data cannot be decoded.
    private nonisolated func pngData(from data: Data) -> Data? {
        guard let image = NSImage(data: data),
              let tiffData = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData) else {
            return nil
        }

        let maxDimension = Self.fallbackMaxDimension
        let width = CGFloat(bitmap.pixelsWide)
        let height = CGFloat(bitmap.pixelsHigh)
        guard width > maxDimension || height > maxDimension else {
            return bitmap.representation(using: .png, properties: [:])
        }

        let scale = maxDimension / max(width, height)
        let newSize = NSSize(width: (width * scale).rounded(), height: (height * scale).rounded())
        guard let resized = ImageThumbnailCache.render(image, size: newSize) else {
            return bitmap.representation(using: .png, properties: [:])
        }
        return resized.tiffRepresentation
            .flatMap { NSBitmapImageRep(data: $0) }?
            .representation(using: .png, properties: [:])
            ?? bitmap.representation(using: .png, properties: [:])
    }
    
    /// Check if a file path points to an image by examining its UTType
    private func isImageFile(_ filePath: String) -> Bool {
        let fileExtension = (filePath as NSString).pathExtension.lowercased()
        guard !fileExtension.isEmpty else { return false }
        
        if let utType = UTType(filenameExtension: fileExtension) {
            return utType.conforms(to: .image)
        }
        return false
    }
    
    /// Read a single image file copied in Finder and store it verbatim (6C):
    /// its bytes and extension are kept exactly as they are on disk — never
    /// re-encoded, whatever the format (JPEG/PNG/HEIC/GIF/WebP/TIFF/...).
    private func processImageFile(_ filePath: String, knownHash: Int, sourceApp: String?) {
        do {
            let fileURL = URL(fileURLWithPath: filePath)
            let fileData = try Data(contentsOf: fileURL)

            // Check for duplicate using hash of the exact bytes.
            let hash = fileData.hashValue
            guard hash != knownHash else {
                // print("[Buffer] Duplicate image file detected: \(filePath)")
                return
            }

            let ext = fileURL.pathExtension.isEmpty ? "png" : fileURL.pathExtension.lowercased()
            let uti = ClipboardItem.uti(forExtension: ext)

            // Save image to disk and add to store
            if let filename = store.saveImage(fileData, fileExtension: ext) {
                var item = ClipboardItem.image(filename: filename, uti: uti, sourceApp: sourceApp)
                item.kind = .image
                DispatchQueue.main.async { [weak self] in
                    self?.lastContentHash = hash
                    self?.store.add(item)
                }
            }
        } catch {
            print("[Buffer] Error processing image file: \(filePath) - \(error)")
        }
    }

    /// Build a `.file` item for any non-single-image set of file URLs from
    /// Finder — one file of any type, or several files/directories of mixed
    /// types. `ClipboardStore.planFileCapture` fingerprints the selection (used
    /// to skip a repeat capture, mirroring the text/image dedupe above) and
    /// `makeFileItem` then decides copy-vs-reference against the configured cap.
    ///
    /// 5A-08: the fingerprint is computed from the URL list **before** anything
    /// is copied, so a repeat ⌘C of the same files costs a few `stat`s instead
    /// of a full second copy that is then thrown away (leaving `files/<uuid>/`
    /// orphaned forever).
    private func processFileURLs(_ urls: [URL], sourceApp: String?, previousFingerprint: String?) {
        guard let plan = store.planFileCapture(from: urls) else { return }
        guard plan.fingerprint != previousFingerprint else { return }
        guard let item = store.makeFileItem(from: plan, sourceApp: sourceApp) else { return }

        DispatchQueue.main.async { [weak self] in
            self?.lastFileFingerprint = plan.fingerprint
            self?.store.add(item)
        }
    }
}
