import Foundation
import AppKit
import Combine
import UniformTypeIdentifiers

/// Monitors the system clipboard for changes and captures new content
class ClipboardWatcher: ObservableObject {
    @Published private(set) var isPaused = false
    
    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private var lastContentHash: Int = 0
    private var ignoreNextChange = false

    /// Fingerprint of the last captured file set, kept separate from
    /// `lastContentHash` (text/image use an `Int`; files use a SHA-256 hex
    /// string from `ClipboardStore.makeFileItem`) so a file capture and a
    /// text/image capture never accidentally compare equal.
    private var lastFileFingerprint: String?
    
    private let pollInterval: TimeInterval = 0.5
    
    // Size thresholds for text handling
    private let inlineTextLimit = 50_000       // 50 KB — store inline
    private let previewLength = 500            // Characters kept as inline preview
    
    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
        
        // Listen for ignore notification (when copying from history)
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleIgnoreNextChange),
            name: .bufferIgnoreNextChange,
            object: nil
        )
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    @objc private func handleIgnoreNextChange() {
        ignoreNextChange = true
    }
    
    func startWatching() {
        guard timer == nil else { return }
        
        timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
        
        RunLoop.main.add(timer!, forMode: .common)
    }
    
    func stopWatching() {
        timer?.invalidate()
        timer = nil
    }
    
    func pause() {
        isPaused = true
    }
    
    func resume() {
        isPaused = false
        lastChangeCount = NSPasteboard.general.changeCount
    }
    
    private func checkClipboard() {
        guard !isPaused else { return }
        
        let pasteboard = NSPasteboard.general
        let currentChangeCount = pasteboard.changeCount
        
        // No change detected
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        
        // Skip if this is a copy from our own history
        if ignoreNextChange {
            ignoreNextChange = false
            return
        }
        
        // Honor org.nspasteboard.ConcealedType/TransientType/AutoGeneratedType
        // (password managers and similar tools opt out of clipboard history
        // this way) — skip the capture entirely, not just the rich flavors.
        if PasteboardFlavors.isConcealed(pasteboard) { return }

        // Get current frontmost app as source
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Check for file URLs from Finder BEFORE the text check (Finder always
        // writes both NSFilenamesPboardType + .string, so we must intercept first).
        // A single image file keeps today's behavior and becomes an `.image`
        // item; any other file, or any count/mix of files, becomes one `.file`
        // item (Phase 3F).
        if let filePaths = pasteboard.propertyList(forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")) as? [String],
           !filePaths.isEmpty {
            if filePaths.count == 1, let filePath = filePaths.first, isImageFile(filePath) {
                // Read and process image file asynchronously to avoid blocking the poll timer
                DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                    self?.processImageFile(filePath, sourceApp: sourceApp)
                }
                return  // Prevent .string branch from also processing this change
            }

            let urls = filePaths.map { URL(fileURLWithPath: $0) }
            // 5A-29: the last fingerprint is read here, on the main thread that
            // owns it, and passed into the background closure instead of being
            // read across threads.
            let previousFingerprint = lastFileFingerprint
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                self?.processFileURLs(urls, sourceApp: sourceApp, previousFingerprint: previousFingerprint)
            }
            return  // Prevent .string branch from also processing this change
        }
        
        // Try to capture text first
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let textSize = text.utf8.count
            
            // Use prefix hash for large text to avoid expensive full-string hashing
            let hashSource = textSize > inlineTextLimit ? String(text.prefix(10_000)) : text
            let hash = hashSource.hashValue
            
            // Skip consecutive duplicates
            if hash != lastContentHash {
                lastContentHash = hash

                // Rich capture (Phase 3D, D5): alongside the plain string,
                // read the RTF/HTML representation and the full raw pasteboard
                // flavors bundle. Applies regardless of inline-vs-file-backed
                // text size — a large plain-text clip can still carry a small
                // RTF/flavors payload worth keeping.
                // Cap the RTF blob like the raw-flavors bundle (review-2B M1): an
                // oversized RTF representation is dropped, the plain text is kept.
                let rtfData = pasteboard.data(forType: .rtf).flatMap { $0.count <= PasteboardFlavors.maxRawBytes ? $0 : nil }
                let htmlData = pasteboard.data(forType: .html)
                let isRich = rtfData != nil || htmlData != nil
                let flavorsData = PasteboardFlavors.capture(pasteboard)

                var item: ClipboardItem
                if textSize <= inlineTextLimit {
                    // Small text: store inline (current behavior)
                    item = ClipboardItem.text(text, sourceApp: sourceApp)
                } else {
                    // Large text: save to file, store preview inline
                    let preview = String(text.prefix(previewLength))
                    guard let filename = store.saveText(text) else { return }
                    item = ClipboardItem.largeText(preview: preview, filename: filename, sourceApp: sourceApp)
                    print("[Buffer] Large text (\(textSize / 1024) KB) saved to file: \(filename)")
                }

                // Detect against the full captured text (not just an inline
                // preview) — we already have it in memory here. 3C's detector
                // result (link/email/phone/color/code) is kept as-is; only a
                // plain `.text` result is upgraded to `.richText`.
                var kind = ContentDetector.detect(for: item, fullText: text)
                if isRich && kind == .text {
                    kind = .richText
                }
                item.kind = kind

                if let rtfData, let filename = store.saveRTF(rtfData, itemID: item.id) {
                    item.rtfFilename = filename
                }
                if let flavorsData, let filename = store.saveFlavors(flavorsData, itemID: item.id) {
                    item.flavorsFilename = filename
                }

                store.add(item)
            }
            return
        }
        
        // Try to capture image
        if let imageData = getImageData(from: pasteboard) {
            let hash = imageData.hashValue
            
            // Skip consecutive duplicates
            if hash != lastContentHash {
                lastContentHash = hash
                
                // Save image to disk
                if let filename = store.saveImage(imageData) {
                    var item = ClipboardItem.image(filename: filename, sourceApp: sourceApp)
                    item.kind = .image
                    store.add(item)
                }
            }
        }
    }
    
    private func getImageData(from pasteboard: NSPasteboard) -> Data? {
        let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff]
        
        for type in imageTypes {
            if let data = pasteboard.data(forType: type) {
                if let image = NSImage(data: data),
                   let tiffData = image.tiffRepresentation,
                   let bitmap = NSBitmapImageRep(data: tiffData),
                   let pngData = bitmap.representation(using: .png, properties: [:]) {
                    return pngData
                }
                return data
            }
        }
        
        return nil
    }
    
    /// Check if a file path points to an image by examining its UTType
    private func isImageFile(_ filePath: String) -> Bool {
        let fileExtension = (filePath as NSString).pathExtension.lowercased()
        guard !fileExtension.isEmpty else { return false }
        
        if let utType = UTType(filenameExtension: fileExtension) {
            return utType.conforms(to: .image)
        }
        return false
    }
    
    /// Read image file from disk, convert to PNG, and store as image item
    private func processImageFile(_ filePath: String, sourceApp: String?) {
        do {
            // Read file bytes
            let fileURL = URL(fileURLWithPath: filePath)
            let fileData = try Data(contentsOf: fileURL)
            
            // Convert to PNG using the same pattern as pasteboard image handling
            guard let image = NSImage(data: fileData),
                  let tiffData = image.tiffRepresentation,
                  let bitmap = NSBitmapImageRep(data: tiffData),
                  let pngData = bitmap.representation(using: .png, properties: [:]) else {
                print("[Buffer] Failed to convert image file: \(filePath)")
                return
            }
            
            // Check for duplicate using hash
            let hash = pngData.hashValue
            guard hash != lastContentHash else {
                // print("[Buffer] Duplicate image file detected: \(filePath)")
                return
            }
            
            // Save image to disk and add to store
            if let filename = store.saveImage(pngData) {
                var item = ClipboardItem.image(filename: filename, sourceApp: sourceApp)
                item.kind = .image
                DispatchQueue.main.async { [weak self] in
                    self?.lastContentHash = hash
                    self?.store.add(item)
                }
            }
        } catch {
            print("[Buffer] Error processing image file: \(filePath) - \(error)")
        }
    }

    /// Build a `.file` item for any non-single-image set of file URLs from
    /// Finder — one file of any type, or several files/directories of mixed
    /// types. `ClipboardStore.planFileCapture` fingerprints the selection (used
    /// to skip a repeat capture, mirroring the text/image dedupe above) and
    /// `makeFileItem` then decides copy-vs-reference against the configured cap.
    ///
    /// 5A-08: the fingerprint is computed from the URL list **before** anything
    /// is copied, so a repeat ⌘C of the same files costs a few `stat`s instead
    /// of a full second copy that is then thrown away (leaving `files/<uuid>/`
    /// orphaned forever).
    private func processFileURLs(_ urls: [URL], sourceApp: String?, previousFingerprint: String?) {
        guard let plan = store.planFileCapture(from: urls) else { return }
        guard plan.fingerprint != previousFingerprint else { return }
        guard let item = store.makeFileItem(from: plan, sourceApp: sourceApp) else { return }

        DispatchQueue.main.async { [weak self] in
            self?.lastFileFingerprint = plan.fingerprint
            self?.store.add(item)
        }
    }
}
