import AppKit

/// Captures and restores the *complete* set of pasteboard representations
/// ("flavors") so a paste is byte-for-byte faithful — preserving app-specific
/// types that the curated text/RTF extraction would otherwise drop.
///
/// Ported from Clipfield's `Clipboard/PasteboardFlavors.swift` (MIT,
/// Copyright 2026 Alex Jolley), see `docs/analysis/clipfield.md` §6, adjusted
/// to this app's naming conventions.
enum PasteboardFlavors {
    /// Don't store raw flavors above this total size; the caller falls back
    /// to the curated RTF/plain representation so the history store stays
    /// bounded (Phase 3D, task brief §1).
    static let maxRawBytes = 16 * 1024 * 1024 // 16 MB

    /// A pasteboard's items, each as a map of type identifier → raw data.
    struct Bundle: Codable {
        var items: [[String: Data]]
    }

    /// Pasteboard type markers used by password managers / clipboard tools
    /// (the nspasteboard.org convention) to opt out of clipboard history.
    /// Honored at capture time so Klip never stores a concealed clipping.
    static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// True when the pasteboard's current contents are marked concealed —
    /// capture should be skipped entirely (not just the rich flavors).
    static func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        let types = pasteboard.types ?? []
        return concealedTypes.contains(where: types.contains)
    }

    /// Serializes every flavor of every pasteboard item, or `nil` if there's
    /// nothing to store or the total exceeds `maxRawBytes`.
    static func capture(_ pasteboard: NSPasteboard) -> Data? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var bundle: [[String: Data]] = []
        var total = 0

        for item in items {
            var map: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    total += data.count
                    // 5A-31: bail as soon as the cap is passed instead of
                    // materialising the whole (arbitrarily large) pasteboard in
                    // memory on the main thread only to discard it.
                    guard total <= maxRawBytes else { return nil }
                    map[type.rawValue] = data
                }
            }
            if !map.isEmpty { bundle.append(map) }
        }

        guard !bundle.isEmpty else { return nil }
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try? encoder.encode(Bundle(items: bundle))
    }

    /// Restores serialized flavors to the pasteboard. Returns `false` if the
    /// data couldn't be decoded (caller should fall back to a curated write).
    @discardableResult
    static func restore(_ data: Data, to pasteboard: NSPasteboard) -> Bool {
        guard let bundle = try? PropertyListDecoder().decode(Bundle.self, from: data),
              !bundle.items.isEmpty else { return false }

        pasteboard.clearContents()
        let pbItems = bundle.items.map { map -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in map {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        return pasteboard.writeObjects(pbItems)
    }
}
